//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppsToken
    {
        public long TokenId { get; set; }
        public short TokenApp { get; set; }
        public System.DateTime TokenCreateTime { get; set; }
        public short TokenState { get; set; }
        public string Token { get; set; }
    }
}
