//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankInfo
    {
        public int BankId { get; set; }
        public int BankUserId { get; set; }
        public System.DateTime BankCreateTime { get; set; }
        public string BankName { get; set; }
        public string BankAccountNo { get; set; }
        public string BankCardNo { get; set; }
        public string BankShabaNo { get; set; }
        public byte[] BankCardPic { get; set; }
        public Nullable<System.Guid> BankCardImageId { get; set; }
        public bool BankIsDeleted { get; set; }
    }
}
