//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarPic
    {
        public int CarPicId { get; set; }
        public System.DateTime CarPicCreateTime { get; set; }
        public int CarCardUserId { get; set; }
        public byte[] CarCardPic { get; set; }
        public bool CarCardIsDeleted { get; set; }
    }
}
