//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityLocation
    {
        public int CityLocId { get; set; }
        public System.DateTime CityLocCreateTime { get; set; }
        public int CityLocType { get; set; }
        public string CityLocShortName { get; set; }
        public string CityLocFullName { get; set; }
        public decimal CityLocLat { get; set; }
        public decimal CityLocLng { get; set; }
        public System.Data.Entity.Spatial.DbGeography CityLocGeo { get; set; }
    }
}
