//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public long ContactId { get; set; }
        public System.DateTime ContactCreateTime { get; set; }
        public bool ContactIsDeleted { get; set; }
        public int ContactDriverUserId { get; set; }
        public int ContactPassengerUserId { get; set; }
        public string ContactLastMsg { get; set; }
        public Nullable<System.DateTime> ContactLastMsgTime { get; set; }
        public Nullable<bool> ContactIsRideAccepted { get; set; }
        public Nullable<bool> SmsSent { get; set; }
        public Nullable<bool> IsPassengerAccepted { get; set; }
    }
}
