//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactScore
    {
        public long CsId { get; set; }
        public long CsUserId { get; set; }
        public System.DateTime CsCreateTime { get; set; }
        public long CsContactId { get; set; }
        public Nullable<short> CsScore { get; set; }
        public string CsComment { get; set; }
    }
}
