//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public int DiscountId { get; set; }
        public string DiscountCode { get; set; }
        public string DiscountTitle { get; set; }
        public System.DateTime DiscountCreateTime { get; set; }
        public System.DateTime DiscountStartTime { get; set; }
        public System.DateTime DiscountEndTime { get; set; }
        public string DiscountDesc { get; set; }
        public Nullable<long> DiscountEvenId { get; set; }
        public int DiscountType { get; set; }
        public Nullable<int> DiscountPercent { get; set; }
    }
}
