//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountUser
    {
        public long DuId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<long> RouteRequestId { get; set; }
        public int DiscountId { get; set; }
        public System.DateTime DuCreateTime { get; set; }
        public short DuState { get; set; }
        public Nullable<long> TransId { get; set; }
    }
}
