//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverRoute
    {
        public long DriverRouteId { get; set; }
        public System.DateTime DrCreateTime { get; set; }
        public long UserId { get; set; }
        public bool DrIsDeleted { get; set; }
        public Nullable<int> CarinfoId { get; set; }
        public long StationRouteId { get; set; }
        public long DrSrcStationId { get; set; }
    }
}
