//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public long EventId { get; set; }
        public System.DateTime EventCreateTime { get; set; }
        public short EventType { get; set; }
        public System.DateTime EventStartTime { get; set; }
        public System.DateTime EventEndTime { get; set; }
        public System.DateTime EventDeadLine { get; set; }
        public string EventCoductorName { get; set; }
        public string EventName { get; set; }
        public string EventAddress { get; set; }
        public decimal EventLat { get; set; }
        public decimal EventLng { get; set; }
        public string EventDesc { get; set; }
        public string EventLink { get; set; }
        public string EventCoductorFamily { get; set; }
        public string EventCoductorMobile { get; set; }
        public Nullable<short> EventConfirmed { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
    }
}
