//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLog
    {
        public long LogId { get; set; }
        public System.DateTime LogCreateTime { get; set; }
        public string LogController { get; set; }
        public string LogAction { get; set; }
        public string LogMessage { get; set; }
    }
}
