//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fanap
    {
        public long FanapId { get; set; }
        public int userId { get; set; }
        public string authorization_code { get; set; }
        public string access_token { get; set; }
        public string refresh_token { get; set; }
        public Nullable<long> fuserId { get; set; }
        public string name { get; set; }
        public string nickName { get; set; }
        public string birthDate { get; set; }
        public string score { get; set; }
        public string joindate { get; set; }
    }
}
