//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterRequest
    {
        public long FilterRequestId { get; set; }
        public long FilterId { get; set; }
        public System.DateTime RCreateTime { get; set; }
        public System.DateTime RStartTime { get; set; }
        public short RState { get; set; }
        public Nullable<long> TripId { get; set; }
        public bool IsActive { get; set; }
        public bool IsCarpool { get; set; }
    }
}
