//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoogleToken
    {
        public long GtokenId { get; set; }
        public System.DateTime GtokenCreateTime { get; set; }
        public long GtokenUserId { get; set; }
        public string GtokenKey { get; set; }
    }
}
