//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public int GroupId { get; set; }
        public System.DateTime GCreateTime { get; set; }
        public bool GIsDeleted { get; set; }
        public long GCreatorUser { get; set; }
        public Nullable<bool> GIsDriverConfirmed { get; set; }
        public Nullable<long> GRouteRequestId { get; set; }
        public System.Data.Entity.Spatial.DbGeography GMidSrc { get; set; }
        public System.Data.Entity.Spatial.DbGeography GMidDst { get; set; }
        public System.Data.Entity.Spatial.DbGeography GAppointGeo { get; set; }
        public Nullable<decimal> GAppointLatitude { get; set; }
        public Nullable<decimal> GAppointLongitude { get; set; }
        public string GAppointAddress { get; set; }
        public Nullable<System.DateTime> AppointTime { get; set; }
        public Nullable<decimal> ConfirmedPrice { get; set; }
    }
}
