//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapImage
    {
        public System.Guid MapShareGuid { get; set; }
        public long RouteRequestId { get; set; }
        public byte[] ShareImage { get; set; }
        public string ShareCaption { get; set; }
        public string SharePath { get; set; }
        public Nullable<long> SeenCount { get; set; }
    }
}
