//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long NotificationId { get; set; }
        public int NotifUserId { get; set; }
        public long NotifCommentId { get; set; }
        public bool IsNotificationSent { get; set; }
        public bool IsNotificationSeen { get; set; }
    }
}
