//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayReq
    {
        public long PayReqId { get; set; }
        public System.DateTime PayReqCreateTime { get; set; }
        public int PayReqUserId { get; set; }
        public double PayReqValue { get; set; }
        public string PayReqAuthority { get; set; }
        public string PayReqStatus { get; set; }
        public string PayReqRefID { get; set; }
        public string TraceNumber { get; set; }
        public string ReferenceNumber { get; set; }
    }
}
