//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteGroup
    {
        public long RouteGroupId { get; set; }
        public System.DateTime RGCreateTime { get; set; }
        public bool RGIsDeleted { get; set; }
        public int GroupId { get; set; }
        public long RGHolderRRId { get; set; }
        public long RGRouteRequestId { get; set; }
        public bool RGIsConfirmed { get; set; }
    }
}
