//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteRequestGPath
    {
        public long RoutePathId { get; set; }
        public int RoutePathIndex { get; set; }
        public System.Guid RouteRequestUId { get; set; }
        public int RoutePathSteps { get; set; }
    }
}
