//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteRequestGRoute
    {
        public long RouteRequestRouteId { get; set; }
        public long RoutePathId { get; set; }
        public int RRRSeq { get; set; }
        public decimal RRRLatitude { get; set; }
        public decimal RRRLongitude { get; set; }
        public long RRRDuration { get; set; }
        public System.Data.Entity.Spatial.DbGeography RRRGeo { get; set; }
    }
}
