//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRTiming
    {
        public long RRTimingId { get; set; }
        public long RouteRequestId { get; set; }
        public System.DateTime RRTimingCreateTime { get; set; }
        public bool RRTimingIsDeleted { get; set; }
        public int RRTimingOption { get; set; }
        public Nullable<System.TimeSpan> RRTheTime { get; set; }
        public Nullable<System.DateTime> RRTheDate { get; set; }
        public Nullable<int> RRDayofWeek { get; set; }
    
        public virtual RouteRequest RouteRequest { get; set; }
    }
}
