//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationRoutePlu
    {
        public long StationRouteId { get; set; }
        public Nullable<long> Five { get; set; }
        public Nullable<long> Six { get; set; }
        public Nullable<long> Seven { get; set; }
        public Nullable<long> Eight { get; set; }
        public Nullable<long> Nine { get; set; }
        public Nullable<long> Ten { get; set; }
        public Nullable<long> Eleven { get; set; }
        public Nullable<long> Twelve { get; set; }
        public Nullable<long> Thirteen { get; set; }
        public Nullable<long> Fourteen { get; set; }
        public Nullable<long> Fifteen { get; set; }
        public Nullable<long> Sixteen { get; set; }
        public Nullable<long> Seventeen { get; set; }
        public Nullable<long> Eighteen { get; set; }
        public Nullable<long> Nineteen { get; set; }
        public Nullable<long> Twenty { get; set; }
        public Nullable<long> TwentyOne { get; set; }
        public Nullable<long> TwentyTwo { get; set; }
        public Nullable<long> TwentyThree { get; set; }
    }
}
