//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        public long StationId { get; set; }
        public long MainStationId { get; set; }
        public string StAdd { get; set; }
        public decimal StLat { get; set; }
        public decimal Stlng { get; set; }
        public System.Data.Entity.Spatial.DbGeography StGeo { get; set; }
    }
}
