//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmLocation
    {
        public long TmLocationId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public decimal TmSrcLat { get; set; }
        public decimal TmSrcLng { get; set; }
        public decimal TmDstLat { get; set; }
        public decimal TmDstLng { get; set; }
    }
}
