//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tran
    {
        public long TransId { get; set; }
        public System.DateTime TransCreateTime { get; set; }
        public short TransType { get; set; }
        public int TransUserId { get; set; }
        public double TransValue { get; set; }
        public string TransDescription { get; set; }
        public Nullable<long> TransPair { get; set; }
    }
}
