//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripRoute
    {
        public long TripRouteId { get; set; }
        public System.DateTime TrCreateTime { get; set; }
        public System.DateTime TrModifyTime { get; set; }
        public long TrTripId { get; set; }
        public long TrRouteRequestId { get; set; }
        public short TrState { get; set; }
    }
}
