//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwBookedTrip
    {
        public System.DateTime TStartTime { get; set; }
        public short TState { get; set; }
        public short TEmptySeat { get; set; }
        public string Passname { get; set; }
        public string PassFamily { get; set; }
        public string DriverName { get; set; }
        public string DriverFamily { get; set; }
        public string srcName { get; set; }
        public string dstName { get; set; }
        public string PassMobile { get; set; }
        public string DriverMobile { get; set; }
        public System.DateTime BrCreateTime { get; set; }
    }
}
