//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwContactScore
    {
        public long CsUserId { get; set; }
        public long ContactId { get; set; }
        public int ContactDriverUserId { get; set; }
        public int ContactPassengerUserId { get; set; }
        public Nullable<bool> ContactIsRideAccepted { get; set; }
        public Nullable<bool> IsPassengerAccepted { get; set; }
        public Nullable<short> CsScore { get; set; }
        public string CsComment { get; set; }
    }
}
