//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwComment
    {
        public string Name { get; set; }
        public string Family { get; set; }
        public int UserId { get; set; }
        public long CommentId { get; set; }
        public System.DateTime CmtCreateTime { get; set; }
        public long GroupId { get; set; }
        public string Comment { get; set; }
    }
}
