//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDiscountUser
    {
        public string DiscountCode { get; set; }
        public string DiscountTitle { get; set; }
        public System.DateTime DiscountCreateTime { get; set; }
        public System.DateTime DiscountStartTime { get; set; }
        public System.DateTime DiscountEndTime { get; set; }
        public string DiscountDesc { get; set; }
        public Nullable<long> DiscountEvenId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<long> RouteRequestId { get; set; }
        public int DiscountId { get; set; }
        public System.DateTime DuCreateTime { get; set; }
        public short DuState { get; set; }
        public Nullable<long> TransId { get; set; }
        public long DuId { get; set; }
        public int DiscountType { get; set; }
        public Nullable<System.DateTime> DuEndTime { get; set; }
        public Nullable<int> DiscountPercent { get; set; }
    }
}
