//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFilterBook
    {
        public string Name { get; set; }
        public string Family { get; set; }
        public string UserName { get; set; }
        public Nullable<long> TripId { get; set; }
        public bool IsActive { get; set; }
        public bool IsCarpool { get; set; }
        public System.DateTime CreateTime { get; set; }
        public long FilterId { get; set; }
        public short RState { get; set; }
        public System.DateTime RStartTime { get; set; }
        public System.DateTime RCreateTime { get; set; }
        public long FilterRequestId { get; set; }
        public bool IsDelete { get; set; }
        public long StationRouteId { get; set; }
        public long FilterUserId { get; set; }
        public Nullable<int> Gender { get; set; }
        public long DstMStationId { get; set; }
        public long SrcMStationId { get; set; }
        public Nullable<long> PayReqId { get; set; }
        public Nullable<short> BookingType { get; set; }
        public Nullable<bool> IsBooked { get; set; }
        public Nullable<System.Guid> UserImageId { get; set; }
    }
}
