//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFilterPlu
    {
        public long FilterId { get; set; }
        public long StationRouteId { get; set; }
        public Nullable<long> Five { get; set; }
        public Nullable<long> Six { get; set; }
        public Nullable<long> Seven { get; set; }
        public Nullable<long> Eight { get; set; }
        public Nullable<long> Nine { get; set; }
        public Nullable<long> Ten { get; set; }
        public Nullable<long> Eleven { get; set; }
        public Nullable<long> Twelve { get; set; }
        public Nullable<long> Thirteen { get; set; }
        public Nullable<long> Fourteen { get; set; }
        public Nullable<long> Fifteen { get; set; }
        public Nullable<long> Sixteen { get; set; }
        public Nullable<long> Seventeen { get; set; }
        public Nullable<long> Eighteen { get; set; }
        public Nullable<long> Nineteen { get; set; }
        public Nullable<long> Twenty { get; set; }
        public Nullable<long> TwentyOne { get; set; }
        public Nullable<long> TwentyTwo { get; set; }
        public Nullable<long> TwentyThree { get; set; }
        public long SrcMStationId { get; set; }
        public long DstMStationId { get; set; }
        public bool IsDelete { get; set; }
        public long FilterUserId { get; set; }
        public Nullable<System.DateTime> LastTimeSet { get; set; }
        public decimal SrcStLat { get; set; }
        public decimal SrcStLng { get; set; }
        public string SrcStName { get; set; }
        public decimal DstStLat { get; set; }
        public decimal DstStLng { get; set; }
        public string DstStName { get; set; }
        public Nullable<long> TripId { get; set; }
    }
}
