//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMainStation
    {
        public long MainStationId { get; set; }
        public string MainStName { get; set; }
        public decimal MainStLat { get; set; }
        public long MainStRadius { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public decimal MainStLng { get; set; }
    }
}
