//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPayRoute
    {
        public int PayReqUserId { get; set; }
        public int PayReqValue { get; set; }
        public string PayReqStatus { get; set; }
        public string PayReqRefID { get; set; }
        public long PayReqId { get; set; }
        public long TripId { get; set; }
        public System.DateTime TStartTime { get; set; }
        public short TState { get; set; }
        public short TEmptySeat { get; set; }
        public long UserId { get; set; }
        public bool DrIsDeleted { get; set; }
        public long DriverRouteId { get; set; }
        public long StationRouteId { get; set; }
        public long DrSrcStationId { get; set; }
    }
}
