//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRouteSuggest
    {
        public string Name { get; set; }
        public string Family { get; set; }
        public double SSrcDistance { get; set; }
        public double SDstDistance { get; set; }
        public string SrcGAddress { get; set; }
        public string SrcDetailAddress { get; set; }
        public decimal SrcLatitude { get; set; }
        public decimal SrcLongitude { get; set; }
        public string DstGAddress { get; set; }
        public string DstDetailAddress { get; set; }
        public decimal DstLatitude { get; set; }
        public decimal DstLongitude { get; set; }
        public int AccompanyCount { get; set; }
        public int CarInfoId { get; set; }
        public string CarType { get; set; }
        public string CarColor { get; set; }
        public bool IsSuggestSent { get; set; }
        public bool IsSuggestSeen { get; set; }
        public bool IsSuggestAccepted { get; set; }
        public bool IsSuggestRejected { get; set; }
        public Nullable<decimal> RRPricingMinMax { get; set; }
        public int RRPricingOption { get; set; }
        public Nullable<int> Gender { get; set; }
        public long RouteRequestId { get; set; }
        public long SelfRouteRequestId { get; set; }
        public bool IsDrive { get; set; }
        public int UserId { get; set; }
        public string CarPlateNo { get; set; }
        public Nullable<long> RecommendPathId { get; set; }
        public Nullable<System.Guid> UserImageId { get; set; }
        public Nullable<System.Guid> SuggestRouteRequestUId { get; set; }
    }
}
