//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRouteGroup
    {
        public System.DateTime RGCreateTime { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public int RRPricingOption { get; set; }
        public Nullable<decimal> RRPricingMinMax { get; set; }
        public bool IsDrive { get; set; }
        public long RGHolderRRId { get; set; }
        public long RouteRequestId { get; set; }
        public bool RGIsConfirmed { get; set; }
        public bool RRIsDeleted { get; set; }
        public decimal SrcLatitude { get; set; }
        public decimal SrcLongitude { get; set; }
        public decimal DstLatitude { get; set; }
        public decimal DstLongitude { get; set; }
        public int AccompanyCount { get; set; }
        public int UserId { get; set; }
        public int GroupId { get; set; }
        public string CarType { get; set; }
        public string CarColor { get; set; }
        public string CarPlateNo { get; set; }
    }
}
