//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRouteProfile
    {
        public long RouteRequestId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string SrcGAddress { get; set; }
        public decimal SrcLongitude { get; set; }
        public decimal SrcLatitude { get; set; }
        public string DstGAddress { get; set; }
        public decimal DstLatitude { get; set; }
        public decimal DstLongitude { get; set; }
        public bool IsDrive { get; set; }
        public Nullable<System.Guid> RouteRequestUId { get; set; }
        public Nullable<decimal> RRPricingMinMax { get; set; }
        public Nullable<System.Guid> UserImageId { get; set; }
        public Nullable<short> VerifiedLevel { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public Nullable<int> Gender { get; set; }
        public string UserName { get; set; }
    }
}
