//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRRPricing
    {
        public long RouteRequestId { get; set; }
        public bool RRPricingIsDeleted { get; set; }
        public int RRPricingOption { get; set; }
        public Nullable<decimal> RRPricingMinMax { get; set; }
        public int UserId { get; set; }
        public long RRPricingId { get; set; }
    }
}
