//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwStation
    {
        public long MainStationId { get; set; }
        public string MainStName { get; set; }
        public long StationId { get; set; }
        public string StAdd { get; set; }
        public decimal StLat { get; set; }
        public decimal StLng { get; set; }
    }
}
