//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwStationRoute
    {
        public long SrcMStationId { get; set; }
        public long DstMStationId { get; set; }
        public long StationRouteId { get; set; }
        public Nullable<long> Duration { get; set; }
        public Nullable<long> DriverPrice { get; set; }
        public Nullable<long> PassPrice { get; set; }
        public string SrcMainStName { get; set; }
        public string DstMainStName { get; set; }
        public decimal DstMainStLat { get; set; }
        public decimal SrcMainStLat { get; set; }
        public decimal SrcMainStLng { get; set; }
        public decimal DstMainStLng { get; set; }
    }
}
