//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSuggestNotification
    {
        public string UserName { get; set; }
        public bool IsSuggestSent { get; set; }
        public bool IsSuggestSeen { get; set; }
        public long RouteRequestId { get; set; }
        public long RouteSuggestId { get; set; }
    }
}
