//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUserInfo
    {
        public int UserId { get; set; }
        public string NationalCode { get; set; }
        public byte[] UserPic { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public Nullable<int> Gender { get; set; }
        public string UserRole { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public Nullable<System.Guid> UserImageId { get; set; }
        public Nullable<short> VerifiedLevel { get; set; }
        public Nullable<long> TripId { get; set; }
        public Nullable<System.Guid> NationalCardImageId { get; set; }
        public Nullable<int> Smscount { get; set; }
        public Nullable<System.Guid> UserUId { get; set; }
    }
}
