//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Withdraw
    {
        public int WithdrawId { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastModification { get; set; }
        public Nullable<System.DateTime> WithdrawDate { get; set; }
        public Nullable<long> TransId { get; set; }
        public double UserBalance { get; set; }
        public double WithdrawAmount { get; set; }
        public int WithdrawState { get; set; }
    }
}
