//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreManager.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راننده حالت سفر را فعال کرد. شما هم برای تایید سفر دکمه حالت سفر را روشن کنید..
        /// </summary>
        public static string ActivateRideState {
            get {
                return ResourceManager.GetString("ActivateRideState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسافر حالت سفر را فعال کرد. شما هم برای تایید سفر دکمه حالت سفر را روشن کنید..
        /// </summary>
        public static string ActivateTripState {
            get {
                return ResourceManager.GetString("ActivateTripState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قرار ملاقات قبلا ثبت شده است و قابل تغییر نیست.
        /// </summary>
        public static string AppointAlreadySet {
            get {
                return ResourceManager.GetString("AppointAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قرار ملاقات هنوز مشخص نشده است.
        /// </summary>
        public static string AppointmentNotSet {
            get {
                return ResourceManager.GetString("AppointmentNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز {0} {1} ساعت {2}.
        /// </summary>
        public static string AtDateTime {
            get {
                return ResourceManager.GetString("AtDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ها ساعت {1}.
        /// </summary>
        public static string AtDayOfWeek {
            get {
                return ResourceManager.GetString("AtDayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ها.
        /// </summary>
        public static string AtDayOfWeekNoTime {
            get {
                return ResourceManager.GetString("AtDayOfWeekNoTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت {0}.
        /// </summary>
        public static string AtTime {
            get {
                return ResourceManager.GetString("AtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با فعال شدن حالت سفر در زمان سفر به صورت خودکار مبلغ کرایه از اعتبار شما به اعتبار راننده منتقل می شود. همچنین در صورت روشن بودن جی پی اس راننده می توانید مسیر راننده را رصد کنید و به موقع به محل قرار برسید.
        /// </summary>
        public static string AutomaticTransaction {
            get {
                return ResourceManager.GetString("AutomaticTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این مسیر در یک گروه ثبت شده است و نمی توانید آن را حذف کنید.
        /// </summary>
        public static string CantDelete {
            get {
                return ResourceManager.GetString("CantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما نمی توانید این گروه را ترک کنید.
        /// </summary>
        public static string CantLeave {
            get {
                return ResourceManager.GetString("CantLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} ({2}).
        /// </summary>
        public static string CarInfoStr {
            get {
                return ResourceManager.GetString("CarInfoStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا عکس کارت ماشین خود را آپلود نمایید.
        /// </summary>
        public static string CarPicNotUploaded {
            get {
                return ResourceManager.GetString("CarPicNotUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد معتبر نیست..
        /// </summary>
        public static string CodeNotExist {
            get {
                return ResourceManager.GetString("CodeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد با موفقیت ثبت شد.
        /// </summary>
        public static string CodeSubmitted {
            get {
                return ResourceManager.GetString("CodeSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد قبلا استفاده شده است.
        /// </summary>
        public static string CodeUsed {
            get {
                return ResourceManager.GetString("CodeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تغییر کرده است.
        /// </summary>
        public static string ConfirmationDenied {
            get {
                return ResourceManager.GetString("ConfirmationDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} .
        /// </summary>
        public static string Creditor {
            get {
                return ResourceManager.GetString("Creditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0}، {1} ساعت {2}.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راننده حالت سفر را غیرفعال کرد. تا اطلاع بعدی قادر به سفر نخواهید بود..
        /// </summary>
        public static string deactivateRideState {
            get {
                return ResourceManager.GetString("deactivateRideState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسافر حالت سفر را غیرفعال کرد. تا اطلاع بعدی با شما همسفر نخواهد بود..
        /// </summary>
        public static string DeactiveTripState {
            get {
                return ResourceManager.GetString("DeactiveTripState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} بدهکار.
        /// </summary>
        public static string Debtor {
            get {
                return ResourceManager.GetString("Debtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قرار ملاقات توسط یکی از راننده های گروه مشخص می شود و هنوز مشخص نشده است.
        /// </summary>
        public static string DriverNotSet {
            get {
                return ResourceManager.GetString("DriverNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی پیش آمده است.
        /// </summary>
        public static string ErrorHappened {
            get {
                return ResourceManager.GetString("ErrorHappened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حذف مسیر مشکلی پیش آمد.
        /// </summary>
        public static string ErrorInDelete {
            get {
                return ResourceManager.GetString("ErrorInDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  {1}  {2}.
        /// </summary>
        public static string EventDateTime {
            get {
                return ResourceManager.GetString("EventDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه توافقی است.
        /// </summary>
        public static string EveryPrice {
            get {
                return ResourceManager.GetString("EveryPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاکتورها صادر شد.
        /// </summary>
        public static string FactorCreated {
            get {
                return ResourceManager.GetString("FactorCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا اطلاعات مربوط به خودروی خود را تکمیل کنید.
        /// </summary>
        public static string FillCarInfo {
            get {
                return ResourceManager.GetString("FillCarInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه ای دریافت نمی کنید.
        /// </summary>
        public static string FreeDrive {
            get {
                return ResourceManager.GetString("FreeDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمی خواهید هزینه ای پرداخت نمایید.
        /// </summary>
        public static string FreeRide {
            get {
                return ResourceManager.GetString("FreeRide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شارژ هدیه حساب {0} به مبلغ {1} ریال.
        /// </summary>
        public static string GiftPayDesc {
            get {
                return ResourceManager.GetString("GiftPayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ظرفیت خودرو اجازه افزودن این پیشنهاد را نمی دهد.
        /// </summary>
        public static string GroupCapacityExceed {
            get {
                return ResourceManager.GetString("GroupCapacityExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات گروه ثبت شد.
        /// </summary>
        public static string GroupConfirmed {
            get {
                return ResourceManager.GetString("GroupConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیشنهاد گروه حذف شد.
        /// </summary>
        public static string GroupSuggestDeleted {
            get {
                return ResourceManager.GetString("GroupSuggestDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور یا رمزعبور نامعتبر است.
        /// </summary>
        public static string InvalidUserPass {
            get {
                return ResourceManager.GetString("InvalidUserPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفر ارزان و راحت با خودروی اشتراکی
        /// با اپلیکیشن «می‌بریم» مسیر روزانه خود را ثبت کنید و با هزینه بسیار پایین به محل کار بروید. شما با این دعوت نامه 3 روز سفر رایگان دریافت می‌کنید و با معرفی کردن 10 نفر می‌توانید تا 30 روز رایگان بین خانه تا محل کار خود جابجا شوید. 
        ///می‌بریم را از http://mibarim.com دریافت کرده و در کد معرفی عبارت {0} را وارد کنید.
        /// </summary>
        public static string InviteLink {
            get {
                return ResourceManager.GetString("InviteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عضویت در گروه هم ماشینی تایید شد.
        /// </summary>
        public static string JoinedGroup {
            get {
                return ResourceManager.GetString("JoinedGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروجی از گروه با موفقیت ثبت شد.
        /// </summary>
        public static string LeavedGroup {
            get {
                return ResourceManager.GetString("LeavedGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای پیوستن به گروه جدید لطفا از گروه فعلی خارج شوید.
        /// </summary>
        public static string LeaveTheGroup {
            get {
                return ResourceManager.GetString("LeaveTheGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا عکس گواهینامه خود را آپلود نمایید.
        /// </summary>
        public static string LicensePicNotUploaded {
            get {
                return ResourceManager.GetString("LicensePicNotUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول {0} بیش از حد معمول است.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر {0} ریال پرداخت می نمایید.
        /// </summary>
        public static string MaxPrice {
            get {
                return ResourceManager.GetString("MaxPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر {0} ریال.
        /// </summary>
        public static string MaxPriceValue {
            get {
                return ResourceManager.GetString("MaxPriceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} متر.
        /// </summary>
        public static string Meter {
            get {
                return ResourceManager.GetString("Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل {0} ریال دریافت می نمایید.
        /// </summary>
        public static string MinPrice {
            get {
                return ResourceManager.GetString("MinPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  حداقل {0} ریال.
        /// </summary>
        public static string MinPriceValue {
            get {
                return ResourceManager.GetString("MinPriceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر {0} نفر می توانند همراه شما باشند.
        /// </summary>
        public static string MiximumAccompany {
            get {
                return ResourceManager.GetString("MiximumAccompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن همراه 11 رقم می باشد.
        /// </summary>
        public static string MobileLength {
            get {
                return ResourceManager.GetString("MobileLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن همراه با 09 شروع می شود.
        /// </summary>
        public static string MobilePattern {
            get {
                return ResourceManager.GetString("MobilePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار مورد درخواست شما یافت نشد.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مانده کافی نمی باشد.
        /// </summary>
        public static string NotRemain {
            get {
                return ResourceManager.GetString("NotRemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع فایل عکس نیست.
        /// </summary>
        public static string NotRightFormat {
            get {
                return ResourceManager.GetString("NotRightFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفری برای شما با این کاربر ثبت نشده است.
        /// </summary>
        public static string NoTrip {
            get {
                return ResourceManager.GetString("NoTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنها می توانید عضو یک گروه باشید..
        /// </summary>
        public static string OnlyOneGroupAllowed {
            get {
                return ResourceManager.GetString("OnlyOneGroupAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای هر مسیر تنها 3 گروه می توانید ایجاد نمایید.
        /// </summary>
        public static string OnlythreeGroupAllowed {
            get {
                return ResourceManager.GetString("OnlythreeGroupAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابتدا مسافران باید اتمام سفر را بزنند.
        /// </summary>
        public static string PassengersFirst {
            get {
                return ResourceManager.GetString("PassengersFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار فیلد {0} نباید کمتر از {2} کاراکتر باشد.
        /// </summary>
        public static string PassLength {
            get {
                return ResourceManager.GetString("PassLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت {0} تومان بابت ثبت سفر.
        /// </summary>
        public static string PayForSetTrip {
            get {
                return ResourceManager.GetString("PayForSetTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شارژ حساب {0} به مبلغ {1} تومان.
        /// </summary>
        public static string PaymentDesc {
            get {
                return ResourceManager.GetString("PaymentDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ پرداختی برای این مسیر {0} ریال می باشد. پس از پرداخت هیچگونه تغییری نمی توانید ایجاد کنید..
        /// </summary>
        public static string paymentMessage {
            get {
                return ResourceManager.GetString("paymentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ پرداخت درست نیست.
        /// </summary>
        public static string PaymentValueNotValid {
            get {
                return ResourceManager.GetString("PaymentValueNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار {0} تومان از اعتبار {1} به اعتبار {2} پرداخت شد.
        /// </summary>
        public static string PayMoneyDesc {
            get {
                return ResourceManager.GetString("PayMoneyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست رد شد.
        /// </summary>
        public static string RejectApplied {
            get {
                return ResourceManager.GetString("RejectApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست تکراری است.
        /// </summary>
        public static string RequestRepeated {
            get {
                return ResourceManager.GetString("RequestRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست با موفقیت ثبت شد.
        /// </summary>
        public static string RequestSubmitted {
            get {
                return ResourceManager.GetString("RequestSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید مشخص شود.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ریال.
        /// </summary>
        public static string Rial {
            get {
                return ResourceManager.GetString("Rial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هم سفری تایید شد.
        /// </summary>
        public static string RideShareAccepted {
            get {
                return ResourceManager.GetString("RideShareAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست هم مسیری ارسال شد.
        /// </summary>
        public static string RideShareRequestSent {
            get {
                return ResourceManager.GetString("RideShareRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما {0}، {1} از {2} به {3} می روید و {4}.
        /// </summary>
        public static string RouteBody {
            get {
                return ResourceManager.GetString("RouteBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر حذف شد.
        /// </summary>
        public static string RouteDeleted {
            get {
                return ResourceManager.GetString("RouteDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر قبلا ثبت شده است.
        /// </summary>
        public static string RouteExist {
            get {
                return ResourceManager.GetString("RouteExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر اشتباه است.
        /// </summary>
        public static string RouteNotExist {
            get {
                return ResourceManager.GetString("RouteNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر پیشنهادی حذف شد.
        /// </summary>
        public static string RouteSuggestDeleted {
            get {
                return ResourceManager.GetString("RouteSuggestDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امتیاز با موفقیت ثبت شد.
        /// </summary>
        public static string ScoreSubmited {
            get {
                return ResourceManager.GetString("ScoreSubmited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رزرو شد.
        /// </summary>
        public static string SeatReserved {
            get {
                return ResourceManager.GetString("SeatReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندلی شما برای مسیر {0} به {1} ساعت {2} رزرو شد.
        /// </summary>
        public static string SeatReservedFor {
            get {
                return ResourceManager.GetString("SeatReservedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من {0}، {1} از {2} به {3} میرم. اگه کسی همین ساعت این مسیر رو میره می تونیم قرار  بذاریم و با هم بریم..
        /// </summary>
        public static string ShareBody {
            get {
                return ResourceManager.GetString("ShareBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر جدید تایید شد و {0} هم مسیر دارید.
        /// </summary>
        public static string similarFound {
            get {
                return ResourceManager.GetString("similarFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیامک دریافت نشده است.
        /// </summary>
        public static string SmsNotReceived {
            get {
                return ResourceManager.GetString("SmsNotReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر پیشنهادی تایید شد.
        /// </summary>
        public static string SuggestAccepted {
            get {
                return ResourceManager.GetString("SuggestAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر جدید ثبت شد اما هم مسیری ندارید. این وبسایت را به دوستانتان معرفی کنید.
        /// </summary>
        public static string suggesttoFriends {
            get {
                return ResourceManager.GetString("suggesttoFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان وارد شده معتبر نیست.
        /// </summary>
        public static string TimeNotValid {
            get {
                return ResourceManager.GetString("TimeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ گذشته است.
        /// </summary>
        public static string TimePassed {
            get {
                return ResourceManager.GetString("TimePassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست توسط راننده پذیرفته شد و در زمان آغاز سفر به شما اطلاع داده خواهد شد.
        /// </summary>
        public static string TripAccepted {
            get {
                return ResourceManager.GetString("TripAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفر فعال نیست.
        /// </summary>
        public static string TripAlreadyDisabled {
            get {
                return ResourceManager.GetString("TripAlreadyDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفر فعال است.
        /// </summary>
        public static string TripAlreadyEnabled {
            get {
                return ResourceManager.GetString("TripAlreadyEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان غیرفعال کردن سفر وجود ندارد. لطفا با پشتیبانی تماس بگیرید.
        /// </summary>
        public static string TripAlreadySet {
            get {
                return ResourceManager.GetString("TripAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفری برای مسیر تعریف شده است.
        /// </summary>
        public static string TripExists {
            get {
                return ResourceManager.GetString("TripExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای نامشخص رخ داده است.
        /// </summary>
        public static string UnknowError {
            get {
                return ResourceManager.GetString("UnknowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه تعریف نشده است.
        /// </summary>
        public static string UnknownGroup {
            get {
                return ResourceManager.GetString("UnknownGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر تعریف نشده است.
        /// </summary>
        public static string UnknownRoute {
            get {
                return ResourceManager.GetString("UnknownRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر قبلا ثبت نام کرده است. لطفا وارد شوید.
        /// </summary>
        public static string UserAlreadyExist {
            get {
                return ResourceManager.GetString("UserAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر ثبت نشده است.
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر پیدا نشد.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا عکس خود را آپلود نمایید.
        /// </summary>
        public static string UserPicNotUploaded {
            get {
                return ResourceManager.GetString("UserPicNotUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای تکمیل سفر منتظر تایید کاربر باشید.
        /// </summary>
        public static string WaitForOtherUserToAccept {
            get {
                return ResourceManager.GetString("WaitForOtherUserToAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خوش آمدید. .
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
