//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreManager.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد همراهان.
        /// </summary>
        public static string AccompanyCount {
            get {
                return ResourceManager.GetString("AccompanyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد همراهان.
        /// </summary>
        public static string AccompanyCount_temp {
            get {
                return ResourceManager.GetString("AccompanyCount_temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ملاقات.
        /// </summary>
        public static string AppointTime {
            get {
                return ResourceManager.GetString("AppointTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حساب.
        /// </summary>
        public static string BankAccount {
            get {
                return ResourceManager.GetString("BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حساب بانکی.
        /// </summary>
        public static string BankAccountNo {
            get {
                return ResourceManager.GetString("BankAccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت عابربانک.
        /// </summary>
        public static string BankCardNo {
            get {
                return ResourceManager.GetString("BankCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام بانک عامل.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال شده به بانک.
        /// </summary>
        public static string Calculated {
            get {
                return ResourceManager.GetString("Calculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عکس پشت کارت ماشین.
        /// </summary>
        public static string CarCardBckPic {
            get {
                return ResourceManager.GetString("CarCardBckPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عکس کارت ماشین.
        /// </summary>
        public static string CarCardPic {
            get {
                return ResourceManager.GetString("CarCardPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ ماشین.
        /// </summary>
        public static string CarColor {
            get {
                return ResourceManager.GetString("CarColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پلاک ماشین.
        /// </summary>
        public static string CarPlate {
            get {
                return ResourceManager.GetString("CarPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع ماشین.
        /// </summary>
        public static string CarType {
            get {
                return ResourceManager.GetString("CarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو شده.
        /// </summary>
        public static string Cenceled {
            get {
                return ResourceManager.GetString("Cenceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدمعرفی.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه مسیر.
        /// </summary>
        public static string ConfirmedPrice {
            get {
                return ResourceManager.GetString("ConfirmedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن تاییدیه.
        /// </summary>
        public static string ConfirmedText {
            get {
                return ResourceManager.GetString("ConfirmedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزییات آدرس مقصد.
        /// </summary>
        public static string DstDetailAddress {
            get {
                return ResourceManager.GetString("DstDetailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس مقصد.
        /// </summary>
        public static string DstGAddress {
            get {
                return ResourceManager.GetString("DstGAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس مقصد روی نقشه.
        /// </summary>
        public static string DstLatitude {
            get {
                return ResourceManager.GetString("DstLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس مقصد روی نقشه.
        /// </summary>
        public static string DstLongitude {
            get {
                return ResourceManager.GetString("DstLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان رویداد.
        /// </summary>
        public static string Edate {
            get {
                return ResourceManager.GetString("Edate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پست الکترونیکی.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک رویداد.
        /// </summary>
        public static string EventLink {
            get {
                return ResourceManager.GetString("EventLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام رویداد.
        /// </summary>
        public static string EventName {
            get {
                return ResourceManager.GetString("EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منقضی.
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رایگان.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمعه.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از .
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس مکان ملاقات.
        /// </summary>
        public static string GAppointAddress {
            get {
                return ResourceManager.GetString("GAppointAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محل ملاقات روی نقشه.
        /// </summary>
        public static string GAppointGeo {
            get {
                return ResourceManager.GetString("GAppointGeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنسیت.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا رمزعبورنامعتبر.
        /// </summary>
        public static string InvalidUserPass {
            get {
                return ResourceManager.GetString("InvalidUserPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داشتن ماشین.
        /// </summary>
        public static string IsDrive {
            get {
                return ResourceManager.GetString("IsDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره گواهینامه.
        /// </summary>
        public static string LicenseNo {
            get {
                return ResourceManager.GetString("LicenseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن همراه.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوشنبه.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به هر قیمتی.
        /// </summary>
        public static string NaMatterPrice {
            get {
                return ResourceManager.GetString("NaMatterPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدملی.
        /// </summary>
        public static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت توافقی.
        /// </summary>
        public static string NoMatterPrice {
            get {
                return ResourceManager.GetString("NoMatterPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هم اکنون.
        /// </summary>
        public static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمزعبور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت شده.
        /// </summary>
        public static string Payed {
            get {
                return ResourceManager.GetString("Payed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه مسیر.
        /// </summary>
        public static string PriceOption {
            get {
                return ResourceManager.GetString("PriceOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست هم مسیری قبول شد.
        /// </summary>
        public static string RideShareAccepted {
            get {
                return ResourceManager.GetString("RideShareAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست هم مسیری ارسال شد.
        /// </summary>
        public static string RideShareRequested {
            get {
                return ResourceManager.GetString("RideShareRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات مسیر.
        /// </summary>
        public static string RouteId {
            get {
                return ResourceManager.GetString("RouteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شنبه.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزییات آدرس مبدا.
        /// </summary>
        public static string SrcDetailAddress {
            get {
                return ResourceManager.GetString("SrcDetailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس مبدا.
        /// </summary>
        public static string SrcGAddress {
            get {
                return ResourceManager.GetString("SrcGAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس مبدا روی نقشه.
        /// </summary>
        public static string SrcLatitude {
            get {
                return ResourceManager.GetString("SrcLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس مبدا روی نقشه.
        /// </summary>
        public static string SrcLongitude {
            get {
                return ResourceManager.GetString("SrcLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت شده.
        /// </summary>
        public static string Submitted {
            get {
                return ResourceManager.GetString("Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هم مسیر پیشنهادی.
        /// </summary>
        public static string Suggested {
            get {
                return ResourceManager.GetString("Suggested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکشنبه.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنجشنبه.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان پایان رویداد.
        /// </summary>
        public static string TimeEnd {
            get {
                return ResourceManager.GetString("TimeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان شروع رویداد.
        /// </summary>
        public static string TimeStart {
            get {
                return ResourceManager.GetString("TimeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان مسیر.
        /// </summary>
        public static string TimingOption {
            get {
                return ResourceManager.GetString("TimingOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به .
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش اعتبار.
        /// </summary>
        public static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفر انجام شد.
        /// </summary>
        public static string TripHappened {
            get {
                return ResourceManager.GetString("TripHappened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سه شنبه.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکل عجیبی پیش اومده.
        /// </summary>
        public static string UnKnownProblem {
            get {
                return ResourceManager.GetString("UnKnownProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استفاده شده.
        /// </summary>
        public static string Used {
            get {
                return ResourceManager.GetString("Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عکس کاربری.
        /// </summary>
        public static string UserPic {
            get {
                return ResourceManager.GetString("UserPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در انتظار راننده هم مسیر.
        /// </summary>
        public static string WaitForDriver {
            get {
                return ResourceManager.GetString("WaitForDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در انتظار مسافر هم مسیر.
        /// </summary>
        public static string WaitForPassenger {
            get {
                return ResourceManager.GetString("WaitForPassenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهارشنبه.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باماشین.
        /// </summary>
        public static string WithCar {
            get {
                return ResourceManager.GetString("WithCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدون ماشین.
        /// </summary>
        public static string WithoutCar {
            get {
                return ResourceManager.GetString("WithoutCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شبا اشتباه است.
        /// </summary>
        public static string WrongShaba {
            get {
                return ResourceManager.GetString("WrongShaba", resourceCulture);
            }
        }
    }
}
